### ISSUE TITLE
旧BP→新BP移行マニュアル　移行データにblocklogフォルダを追加する

### ISSUE THREAD

**Issue by btbf** [akyo3/Extends-SJG-Knowledge#2]
https://github.com/akyo3/Extends-SJG-Knowledge/blob/main/BP_Relocation.md

https://github.com/akyo3/Extends-SJG-Knowledge/blob/ffa25002ee6a74b93de1def34a2b5ed8a3872e04/BP_Relocation.md?plain=1#L207

過去のブロック生成履歴の取得は、`cncli.sh init` ではなく旧BPの`~/cnode/guild-db/blocklog` をコピーする方法が望ましい。

■理由
`cncli.sh init`で取得する場合、実績のみしか取得できず過去エポックの `Ideal` `Luck` が取得できないため

**Comment by AichiStakePool** [comment]
ありがとうございます！
こちらは、コピーをして新BPの
~/cnode/guild-db/blocklog
の中にblocklogファイルを入れておけば、生成履歴が自動取得されるようになっていますか？

**Comment by btbf** [comment]
自動取得というか、blocklogの中にDBファイルがあるので過去の生成履歴はそこにすでに入ってる形なので、
新BPにコピーして、blocks.sh立ち上げると旧BPの状態がそのまま引き継がれます。
あと、blocklogだけじゃなく、`~/cnode/guild-db/` ごとコピーすると cncliも最初から同期しなくて済みます。

**Comment by AichiStakePool** [comment]
ありがとうございます。
もしかして、BP移設の際に「guil-db」「script」の両フォルダは、旧BPからまるごとコピーして大丈夫だったりしますか？

**Comment by btbf** [comment]
はい。大丈夫です

**Comment by AichiStakePool** [comment]
ありがとうございます。追記しておきます。
「guild-db」「script」の両フォルダはまるまるコピーがいいですね。
手順2-11,12をすっとばせそうですし、BTBFさんの言われる過去ブロック生成履歴取得が楽ですし、
何よりcncliの同期が不要なのは大きいです。

（serviceファイルを作成＆起動のコマンドは打たなきゃいけないけど）

**Comment by akyo3** [comment]
メモ
一応envのupdatecheckをNにするコマンドもいれておく

```
sed -i $NODE_HOME/scripts/env \
    -e '1,73s!#UPDATE_CHECK="Y"!UPDATE_CHECK="N"!'
```

**Comment by AichiStakePool** [comment]
envファイルについては、旧BPからそのままコピーしたほうが早いですね。
あと手順2-11,12をすっとばせる、と上の私のメモでは書きましたが
さすがにすっ飛ばせなさそうな気がします。
例えばserviceファイルなどはきちんとシステムフォルダにコピーしなければいけませんし。
ということで、「script」フォルダをまるまるコピーするという記述は避けて、普通に手順2-11を行ってもらった方が良さそうですね。
また手順2-12はすぐに終わるので「すっとばす」メリットはあまり感じられません。なのでこちらも行ってもらった方がいいかと。

現在円高によりAichiプールを移動させていますが、guild-dbのコピーにめっちゃ時間がかかっています（FileZilla利用中）💦これは一律に旧BPから移動する必要はないとおもいましたがどうなんだろうか…。

**Comment by AichiStakePool** [comment]
akyoさんへ

コマンド入れておきました。
![image](https://user-images.githubusercontent.com/99731543/191971475-8f725865-25b4-4c1f-9a8b-0805c70fed50.png)

**Comment by AichiStakePool** [comment]
guild-dbのコピーにめっちゃ時間がかかっていますが、これってもしかしてローカルではなくrsinc+rss設定を利用して他のBPとロケーションが近ければ他のBPから持ってきてよかったりしますかね？

**Comment by akyo3** [comment]
@AichiStakePool 
別ファイルにて少し修正させていただきましたので、お手隙の際にでもご確認いただければと思います。

https://github.com/akyo3/Extends-SJG-Knowledge/blob/main/Test-BP_Relocation.md

**Comment by AichiStakePool** [comment]
（返信がめっちゃ遅れてすみません、気づきませんでした）
ありがとうございます！確認しました。こちらの形式で大丈夫だと思います。

**Comment by akyo3** [comment]
ありがとうございます！ではTest-BP~ をBP_Re~と差し替えます。

**Comment by akyo3** [comment]
差替えました！これにてクローズします。
