### ISSUE TITLE
旧BP→新BP移行マニュアル　BP停止時にノード自動起動も停止しておく

### ISSUE THREAD

**Issue by btbf** [akyo3/Extends-SJG-Knowledge#3]
https://github.com/akyo3/Extends-SJG-Knowledge/blob/ffa25002ee6a74b93de1def34a2b5ed8a3872e04/BP_Relocation.md?plain=1#L201

サーバーをシャットダウンするが、万一起動してしまったときのための対策
```
sudo systemctl stop cardano-node
```
```
sudo systemctl disable cardano-node
```

**Comment by AichiStakePool** [comment]
完了しました！

**Comment by AichiStakePool** [comment]
![image](https://user-images.githubusercontent.com/99731543/189639705-acae9742-92e4-4ce6-9c89-34adb8d42b26.png)
こちらも追加しました。合わせて確認していただけると幸いです。

**Comment by akyo3** [comment]
問題なさそうなのでクローズ
