### ISSUE TITLE
guild-db移設の注意書きについて

### ISSUE THREAD

**Issue by btbf** [akyo3/Extends-SJG-Knowledge#5]
https://github.com/akyo3/Extends-SJG-Knowledge/blob/4cd4a76ff01d92731b1143a16fa3342b5df0e211/BP_Relocation.md?plain=1#L299

guild-dbを旧BPから移行しないと、過去の「Ideal」「Luck」が全て消えます(この２つは再取得できません)ので、必ず移行する表現にして下さい。SFTPソフトを使えばそんなに時間かかりません。

**Comment by akyo3** [comment]
> https://github.com/akyo3/Extends-SJG-Knowledge/blob/4cd4a76ff01d92731b1143a16fa3342b5df0e211/BP_Relocation.md?plain=1#L299
> 
> guild-dbを旧BPから移行しないと、過去の「Ideal」「Luck」が全て消えます(この２つは再取得できません)ので、必ず移行する表現にして下さい。SFTPソフトを使えばそんなに時間かかりません。

---
https://github.com/akyo3/Extends-SJG-Knowledge/blob/82f6d5b0998fa32e5d046b144c1048db4fa2fb78/BP_Relocation.md?plain=1#L256-L257

指摘行は、削除して、旧BPから新BPへ各ファイルを移動する箇所の表の下部に追記。またFileZillaのセットアップのURLも併せて追記。

ありがとうございます。その他あれば引き続きよろしくお願いします。
