### ISSUE TITLE
cncli.db削除コマンド追記

### ISSUE THREAD

**Issue by btbf** [akyo3/Extends-SJG-Knowledge#6]
https://github.com/akyo3/Extends-SJG-Knowledge/blob/4cd4a76ff01d92731b1143a16fa3342b5df0e211/BP_Relocation.md?plain=1#L295-L297

旧BPからコピーしたcncli.dbで同期不具合が発生する場合があるので、ブロックログ導入前にcncli.dbを削除するコマンドを追記してください。(guild-dbは消さない)

```
rm $NODE_HOME/guild-db/cncli/cncli.db
```

**Comment by akyo3** [comment]
> https://github.com/akyo3/Extends-SJG-Knowledge/blob/4cd4a76ff01d92731b1143a16fa3342b5df0e211/BP_Relocation.md?plain=1#L295-L297
> 
> 旧BPからコピーしたcncli.dbで同期不具合が発生する場合があるので、ブロックログ導入前にcncli.dbを削除するコマンドを追記してください。(guild-dbは消さない)
> 
> ```
> rm $NODE_HOME/guild-db/cncli/cncli.db
> ```

---
ブロックログの設定前に追記しました。
ありがとうございます。その他あれば引き続きよろしくお願いします。

https://github.com/akyo3/Extends-SJG-Knowledge/blob/82f6d5b0998fa32e5d046b144c1048db4fa2fb78/BP_Relocation.md?plain=1#L294-L297
